### ISSUE TITLE
Query Length Restriction inadequate

### ISSUE THREAD

**Issue by Flybel** [man90es/BDO-REST-API#13]
It seems like the restriction of /adventurer/search query strings to no more than 16 characters is inadequate. Family names with more than 16 characters exist and are searchable on the website, so I believe this restriction should be removed.

I'm not sure why the restriction exists or if there is currently a length restriction for new accounts. The instance I am aware of which is longer than 16 characters resulted from a name change due to the old name breaking the rules. But clearly such names are possible and the website search supports them.

**Comment by man90es** [comment]
The length validation comes from a naming hint that was in the game a few years ago. Perhaps they changed something, or the rules were different for family name and character name from the start. Can you provide some examples of family names longer than 16 characters?

**Comment by Flybel** [comment]
I scanned a few guild profiles looking for names longer than 16 chars, trying to find more examples, but apart from the aforementioned user whose name was changed by staff I didn't find any. So I contacted PA support asking about this user and if the length restriction for names is still valid. This was confirmed and the user's family name has been changed again now.

> As for your question, all the names needs to stay under the limit of 16 characters, and there's no exception for this.

Although I assume that longer names don't cause problems on the website in particular, I hope that PA staff usually enforces the length correctly, in which case the length validation can probably stay?

**Comment by man90es** [comment]
That's an interesting case, thanks for doing the research. I will keep the length validation for now (less requests to BDO servers = lower chance of getting banned), but I also added this bug to the [list of known problems](https://github.com/man90es/BDO-REST-API/blob/master/docs/brokenStuff.md).

If you find any other bugs or inconsistensies, feel free to create another issue!
