### ISSUE TITLE
Change minimum number of characters for 3

### ISSUE THREAD

**Issue by huarlensouza** [man90es/BDO-REST-API#31]
Endporint: /v1/adventurer/search

When searching for adventurers with 2 characters it is returning "false" due to the minimum quantity, it turns out that it is possible to create a family name with 2 digits

Examples:
Region: SA
FamilyName: L1

Region: SA
FamilyName: xR

if len(query[0]) < 3 || len(query[0]) > 16 {
	return query[0], false
}

validators/ValidateAdventurerNameQueryParam.go

![image](https://github.com/user-attachments/assets/1a315f17-a234-418d-a4fc-8156f93eb7a1)

**Comment by man90es** [comment]
Thanks for bringing this to my attention, looks like different regions can have different limits, because there's no such family names on EU or NA. I will change the validator soon
