### ISSUE TITLE
API returns status 404 for guilds that exist

### ISSUE THREAD

**Issue by ProtDos** [man90es/BDO-REST-API#7]
Nearly ever guild gets a 404 error, even though playblackdesert shows them as valid. Maybe they changed api?

**Comment by man90es** [comment]
It looks like Pearl Abyss have restricted my server's access to their site. For now, I turned off the API and will investigate the issue further.

In the meantime, you can try self-hosting, but considering current circumstances, it's risky.

**Comment by man90es** [comment]
Apparently, Pearl Abyss started using Imperva protection against bots — it was present on BDO website in the past but then they removed it and now added it back in.

I turned the API back on, so it may work for some time. Still looking for solutions.

**Comment by ProtDos** [comment]
Thank you for solving it!
